version: "3.8"

services:
  db:
    image: neo4j:2025.03-community
    container_name: gd-roadmap-service-db
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
#    volumes:
#      - ./db-data:/data
    healthcheck:
      test: [ "CMD-SHELL", "neo4j status" ]
      interval: 10s
      timeout: 5s
      retries: 10