linkedin-config:
  board-name: "Example Job Board"
  base-url: "https://example.com/jobs"
  search-properties:
    keyword-property: "keywords"
    location-property: "location"
    experience-level-property: "experienceLevel"
    date-posted-property: "datePosted"
  job-listings-container-element-locator:
    locator-type: "cssSelector"
    locator-string: ".job-listings"
  job-item-element-locator:
    locator-type: "cssSelector"
    locator-string: ".job-listings"
  job-selectors:
    - field: JOB_ID
      selector:
        element-locator:
          locator-type: "cssSelector"
          locator-string: ".job-listings"
        attribute-selector:
          attribute-type: "id"
          attribute-name: "data-job-id"
  page-load-wait-time: 10
  element-wait-time: 5
  max-pages: 5
  request-delay-ms: 1000