spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

server:
  servlet:
    context-path: /

logging:
  level:
    org:
      hibernate: DEBUG
      springframework: DEBUG
    com:
      jwtdemo: TRACE
  file:
    name: logs/spring-boot-app.log
    path: logs
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB