spring:
  application:
    name: gd-discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}


# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false     # it shouldn't register itself
    fetch-registry: false           # it shouldn't fetch itself

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
