version: "3.8"

services:
  db:
    image: postgres:17.4-alpine
    container_name: gd-prompt-processing-service
    restart: unless-stopped
    environment:
      POSTGRES_DB: gd-prompt-processing-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    env_file:
      - .env
#    volumes:
#      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 30s

#volumes:
#  db-data:
#    driver: local