spring:
  application:
    name: gd-board-scraper-service
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      authentication-database: ${MONGODB_AUTH:admin}
#    servlet:
#      multipart:
#        enabled: true
#        max-file: 10MB
#        request-size: 10MB
server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: info


selenium:
  grid:
    url: http://${SELENIUM_GRID_HOST:localhost}:${SELENIUM_GRID_PORT:4444}

#scraper:
#  linkedin:
#    selectors:
#      job-urn-elementLocator: base-card
#      title-elementLocator: base-search-card__title
#      company-elementLocator: base-search-card__subtitle
#      location-elementLocator: job-search-card__location
##      salary-elementLocator: .jobs-unified-top-card__salary-details
##      description-elementLocator: .jobs-description-content__text
#      date-posted-elementLocator: job-search-card__listdate
#    attributes:
#      job-urn-attribute: data-entity-urn
#      date-posted-attribute: data-entity-urn


scraper:
  linkedin:
    elements:
      id:
        selector: base-card
        attribute: data-entity-urn
        pattern: /([^\/]+)$/
      title:
        selector: base-search-card__title
      company:
        selector: base-search-card__subtitle
      location:
        selector: job-search-card__location
#      salary:
#        elementLocator: .jobs-unified-top-card__salary-details
#      description:
#        elementLocator: .jobs-description-content__text
      date-posted:
        selector: job-search-card__listdate
        attribute: datetime