version: '3.8'

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: gd-job-scraper-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - selenium
#      - mongodb
#    networks:
#      - gd-job-scraper-network
#    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s

  mongodb:
    image: mongo:latest
    container_name: gd-market-analysis-mongo
    restart: unless-stopped
    networks:
      - gd-job-scraper-network
    environment:
      MONGO_INITDB_DATABASE: gd-market-analysis-mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
#      - ./seeder.js:/docker-entrypoint-initdb.d/seeder.js:ro
#      - ./mongo-entrypoint:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local

networks:
  gd-job-scraper-network:
    driver: bridge